db = db.getSiblingDB('monafit_db');
   db.createCollection('views');
   db.createCollection('teams');
   db.createCollection('activity');
   db.createCollection('leaderboard');
   db.createCollection('workouts');
   db.users.createIndex({ email: 1 }, { unique: true });
   db.teams.createIndex({ name: 1 }, { unique: true });
   db.activity.createIndex({ activity_id: 1 }, { unique: true });
   db.leaderboard.createIndex({ leaderboard_id: 1 }, { unique: true });
   db.workouts.createIndex({ workout_id: 1 }, { unique: true });